#include"employee.h"
void employee::setdata(string  name,int age,string emp_id){
    this-> name=name;
    this-> age=age;
    this-> emp_id=emp_id;
}
void employee::display(){
    cout<<"name : "<<name<<endl;
    cout<<"age : "<<age<<endl;
    cout<<"emp_id : "<<emp_id<<endl;
}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           